### PR TITLE
7.4.1

### PR DESCRIPTION
**Pull request by tizianolattisi**
Hi,
I hope this my work on the 7.4.1 can be useful.

Have a nice day
Tiziano

### CODE REVIEW

**Comment by JeremJR** [comment]
Hi,

Thanks for your work.
We will review it and keep you posted.

Have a nice day

**Comment by JeremJR** [comment]
Hi,

We have just published a similar work for version 7.4.0
We have the same approach as yours except for launching the application server. Actually we prefer not to modify the startup.sh script coming from Tomcat.
Please also note that you removed JAVA_OPTS management through setenv.sh and we want to keep this option.
With 7.4.0 work we also removed postgres and mysql jdbc drivers from Docker build as they are already provided in the bundle's setup/lib directory.
Therefore we suggest you to adapt you PR accordingly for version 7.4.1.

Have a nice week end

**Comment by tizianolattisi** [comment]
Thanks a lot for your reply JereJR.
I corrected the conflicts according to your indications, and I made a couple of tests.
Now I think the patch could be fine.

Have a nice day!
T

**Comment by JeremJR** [comment]
Hi,
Thanks the corresponding PR will be reviewed by the Docker Team :
https://github.com/docker-library/official-images/pull/2598
Have a nice day

**Pull request merged**
